### ISSUE TITLE
bag8 is searching for a missing /etc/default/docker file

### ISSUE THREAD

**Issue by brunobord** [novafloss/bag8#48]
on my Ubuntu laptop:

```
$ bag8 setup
No config found at: /home/novapost/.config/bag8.yml.
Loads default values.
Traceback (most recent call last):
  File "/home/novapost/.virtualenvs/TEST/bin/bag8", line 10, in <module>
    sys.exit(bag8())
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/novapost/.virtualenvs/TEST/src/bag8/bag8/cli.py", line 221, in setup
    Tools().update_docker_conf()
  File "/home/novapost/.virtualenvs/TEST/src/bag8/bag8/tools.py", line 36, in update_docker_conf
    with open(conf_path) as f:
IOError: [Errno 2] No such file or directory: u'/etc/default/docker'
```

I've found a ``/etc/default/docker.io`` file. IMHO, this filepath should be a configurable parameter.

**Comment by toopy** [comment]
idem: https://github.com/novafloss/bag8/issues/51#issuecomment-121916368

**Comment by toopy** [comment]
cf.: #47
