### ISSUE TITLE
bag8 dns connection error

### ISSUE THREAD

**Issue by brunobord** [novafloss/bag8#53]
when trying to run ``bag8 dns``, it looks like bag8 is trying to connect to the dnsdock server to check if it's already running. if it does, I think it does nothing. but if it's not running, there's an untrapped connection error:

```
$ bag8 dns
No config found at: /home/novapost/.config/bag8.yml.
Loads default values.
Traceback (most recent call last):
  File "/home/novapost/.virtualenvs/TEST/bin/bag8", line 10, in <module>
    sys.exit(bag8())
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/novapost/Projets/TEST/figfiles/src/bag8/bag8/cli.py", line 88, in dns
    result = Tools().dns()
  File "/home/novapost/Projets/TEST/figfiles/src/bag8/bag8/tools.py", line 100, in dns
    if not inspect('dnsdock')['State']['Running']:
  File "/home/novapost/Projets/TEST/figfiles/src/bag8/bag8/utils.py", line 63, in inspect
    return client.inspect_container(container)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/docker/client.py", line 474, in inspect_container
    self._get(self._url("/containers/{0}/json".format(container))),
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/novapost/.virtualenvs/TEST/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

It may sound a bit silly: to run/restart a service, it's okay to check if it's running, but it's not okay to FAIL if it doesn't.

**Comment by toopy** [comment]
cf.: #47
